[build]
  command = "cd client && npm install && npm run build"
  publish = "client/build"
  base = "."

[dev]
  command = "npm run dev"
  port = 3000

[[redirects]]
  from = "/api/*"
  to = "https://cooltab-backend.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
